//! 构建脚本。
//!
//! 负责两件事：
//!
//! 1. 让 `frontend/` 的内容变化真正反映到 exe 里（tauri-build 默认不监控该目录）；
//! 2. **自动同步缓存戳**——改完前端直接编译即可，不再需要手工改四处版本号。
//!
//! # 为什么必须有缓存戳
//! WebView2 会缓存 `tauri.localhost` 下的 HTML/CSS/JS。即使 exe 里嵌入的是新资源，
//! 运行中的 WebView 仍可能拿旧的，必须让资源 **URL** 变化才能穿透缓存。因此
//! `index.html` / `styles.css` / `app.js` 三处引用都带 `?v=<指纹>`。
//!
//! # 关键：哈希前必须先归一化
//! 本脚本会把算出的指纹**回写**到源码里。若直接哈希原始内容，就会形成
//! 「回写版本号 → 文件内容变化 → 指纹变化 → 再次回写」的死循环，
//! 结果是每次编译都改版本号、每次都强制重编整个 crate。
//! 故哈希前先剔除缓存戳本身（见 [`normalize`]），使「仅改版本号」不影响指纹。

use std::path::{Path, PathBuf};

const FRONTEND: &str = "../frontend";
const FE_VER_PREFIX: &str = "const FE_VER = \"";
/// 需要同步缓存戳的文件（路径相对 build.rs 的工作目录，即 src-tauri/）
const TARGETS: &[&str] = &["../frontend/index.html", "../frontend/app.js", "tauri.conf.json"];
/// 主程序权限清单（自动补齐 `allow-*` 项）
const CAPABILITIES: &str = "capabilities/default.json";

/// 剔除内容里的缓存戳，保证「仅改版本号」不改变指纹。
///
/// 覆盖两种写法：资源引用的 `?v=<hex>` 与日志标记的 `const FE_VER = "v<hex>"`。
fn normalize(s: &str) -> String {
    let mut s = strip_query_ver(s);
    if let Some(p) = s.find(FE_VER_PREFIX) {
        let start = p + FE_VER_PREFIX.len();
        if let Some(off) = s[start..].find('"') {
            let end = start + off;
            s = format!("{}{}\"{}", &s[..p], FE_VER_PREFIX, &s[end..]);
        }
    }
    s
}

/// 把 `?v=` 后跟随的十六进制数字串抹掉，只留 `?v=`。
fn strip_query_ver(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(p) = rest.find("?v=") {
        out.push_str(&rest[..p]);
        out.push_str("?v=");
        let b = rest.as_bytes();
        let mut i = p + 3;
        while i < b.len() && (b[i] as char).is_ascii_hexdigit() {
            i += 1;
        }
        rest = &rest[i..];
    }
    out.push_str(rest);
    out
}

/// 把缓存戳写入内容：`?v=` 后的数字换成 `ver`，FE_VER 的值换成 `v{ver}`。
fn apply_ver(s: &str, ver: &str) -> String {
    let mut out = String::with_capacity(s.len() + 128);
    let mut rest = s;
    loop {
        let q = rest.find("?v=");
        let f = rest.find(FE_VER_PREFIX);
        match (q, f) {
            (Some(q), Some(f)) if f < q => rest = apply_fe(rest, ver, &mut out),
            (Some(_), _) => rest = apply_query(rest, ver, &mut out),
            (None, Some(_)) => rest = apply_fe(rest, ver, &mut out),
            _ => {
                out.push_str(rest);
                return out;
            }
        }
    }
}

/// 处理一处 `?v=`，返回剩余未处理部分。
fn apply_query<'a>(rest: &'a str, ver: &str, out: &mut String) -> &'a str {
    let p = rest.find("?v=").unwrap();
    out.push_str(&rest[..p]);
    out.push_str("?v=");
    out.push_str(ver);
    let b = rest.as_bytes();
    let mut i = p + 3;
    while i < b.len() && (b[i] as char).is_ascii_hexdigit() {
        i += 1;
    }
    &rest[i..]
}

/// 处理一处 `const FE_VER = "..."`，返回剩余未处理部分。
fn apply_fe<'a>(rest: &'a str, ver: &str, out: &mut String) -> &'a str {
    let p = rest.find(FE_VER_PREFIX).unwrap();
    out.push_str(&rest[..p]);
    out.push_str(FE_VER_PREFIX);
    out.push('v');
    out.push_str(ver);
    out.push('"');
    let start = p + FE_VER_PREFIX.len();
    let off = rest[start..].find('"').unwrap();
    &rest[start + off + 1..]
}

/// 计算 frontend 目录的内容指纹（FNV-1a，对归一化后的文本求哈希）。
fn frontend_fingerprint(dir: &Path) -> u64 {
    fn walk(dir: &Path, h: &mut u64, count: &mut u64) {
        let Ok(rd) = std::fs::read_dir(dir) else { return };
        // 排序：read_dir 的返回顺序不保证，不排序会导致同一份内容算出不同指纹
        let mut entries: Vec<PathBuf> = rd.flatten().map(|e| e.path()).collect();
        entries.sort();
        for p in entries {
            if p.is_dir() {
                walk(&p, h, count);
            } else if let Ok(data) = std::fs::read(&p) {
                let norm = normalize(&String::from_utf8_lossy(&data));
                for &b in norm.as_bytes() {
                    *h ^= b as u64;
                    *h = h.wrapping_mul(0x1_0000_01b3);
                }
                *h ^= norm.len() as u64;
                *count += 1;
            }
        }
    }
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    let mut count: u64 = 0;
    walk(dir, &mut h, &mut count);
    h ^ count
}

/// 把缓存戳同步到源文件。只在内容真的变化时写盘（避免无谓的 mtime 变动与 git 脏）。
fn sync_cache_buster(ver: &str) -> usize {
    let mut written = 0;
    for rel in TARGETS {
        let Ok(orig) = std::fs::read_to_string(rel) else {
            println!("cargo:warning=缓存戳同步跳过：读不到 {rel}");
            continue;
        };
        let next = apply_ver(&orig, ver);
        if next == orig {
            continue;
        }
        match std::fs::write(rel, next.as_bytes()) {
            Ok(()) => written += 1,
            Err(e) => println!("cargo:warning=缓存戳同步失败（{rel}）：{e}"),
        }
    }
    written
}

/// 从 `src/main.rs` 解析所有 `#[tauri::command]` 的函数名（升序去重）。
///
/// 这份名单是**单一真相源**，有两个用途：交给 tauri-build 生成 ACL 权限
/// （`permissions/autogenerated/*.toml`）、以及自动补齐 capabilities 里的
/// `allow-*` 项。
///
/// 硬编码名单的代价已经付过一次：2026-09-11 新增 `get_storage_info` /
/// `run_maintenance` 时忘了同步这份名单，结果**编译照过、后端调度器内部调用
/// 也正常**（内部调用不走 IPC、不受 ACL 限制），只有前端点按钮时才报
/// "Command run_maintenance not allowed by ACL"。
fn command_names() -> Vec<String> {
    let src = std::fs::read_to_string("src/main.rs").expect("读不到 src/main.rs");
    let mut names: Vec<String> = Vec::new();
    let mut rest: &str = &src;
    while let Some(p) = rest.find("#[tauri::command") {
        let Some(off) = rest[p..].find(']') else { break };
        let mut cur = &rest[p + off + 1..];
        // 属性与 fn 之间可能夹着别的属性或行注释
        loop {
            let t = cur.trim_start();
            if t.starts_with("//") {
                cur = match t.find('\n') {
                    Some(o) => &t[o + 1..],
                    None => "",
                };
                continue;
            }
            if t.starts_with("#[") {
                cur = match t.find(']') {
                    Some(o) => &t[o + 1..],
                    None => "",
                };
                continue;
            }
            break;
        }
        let t = cur.trim_start();
        let t = t.strip_prefix("pub ").unwrap_or(t);
        let t = t.strip_prefix("async ").unwrap_or(t);
        if let Some(n) = t.strip_prefix("fn ") {
            let name: String = n
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                names.push(name);
            }
        }
        rest = &rest[p + off + 1..];
    }
    names.sort();
    names.dedup();
    names
}

/// capabilities 里补齐缺失的 `allow-<kebab>`，返回补的条数。
///
/// 只在确实缺失时写盘（幂等），否则「改文件 → 触发 build script 重跑 →
/// 又改文件」会形成死循环。
fn sync_capabilities(cmds: &[String]) -> usize {
    let Ok(orig) = std::fs::read_to_string(CAPABILITIES) else {
        println!("cargo:warning=权限同步跳过：读不到 {CAPABILITIES}");
        return 0;
    };
    let crlf = orig.contains("\r\n");
    let eol = if crlf { "\r\n" } else { "\n" };
    let mut next = orig.clone();
    let mut added = 0;
    for c in cmds {
        let perm = format!("allow-{}", c.replace('_', "-"));
        if next.contains(&format!("\"{perm}\"")) {
            continue;
        }
        // 插到 permissions 数组最后一项之后：最后一个引号即该项的结束引号
        let Some(p) = next.rfind('"') else { continue };
        next.insert_str(p + 1, &format!(",{eol}    \"{perm}\""));
        added += 1;
    }
    if added > 0 && next != orig {
        if let Err(e) = std::fs::write(CAPABILITIES, next.as_bytes()) {
            println!("cargo:warning=权限同步失败（{CAPABILITIES}）：{e}");
            return 0;
        }
    }
    added
}

fn main() {
    // 前端资源目录变化时强制重跑 tauri-build（把 HTML/CSS/JS 重新嵌入 exe）。
    // tauri-build 默认不监控 frontend/，不写这条会导致改前端文件后 exe 里仍是旧资源。
    println!("cargo:rerun-if-changed=../frontend");
    println!("cargo:rerun-if-changed=../frontend/hover_card.html");
    println!("cargo:rerun-if-changed=../frontend/index.html");
    println!("cargo:rerun-if-changed=../frontend/app.js");
    println!("cargo:rerun-if-changed=../frontend/styles.css");

    let fp = frontend_fingerprint(Path::new(FRONTEND));
    // 折叠成 32 位：高低位异或，避免只用低位（FNV-1a 的低位散列质量相对差）
    let ver = format!("{:08x}", (fp >> 32) as u32 ^ fp as u32);

    // 必须在 tauri_build 之前回写：它是读 tauri.conf.json 生成 context 的，
    // 晚一步则本次嵌入 exe 的仍是带旧戳的资源，改动要编译两次才生效。
    let n = sync_cache_buster(&ver);
    if n > 0 {
        println!("cargo:warning=已自动同步 {n} 处缓存戳 -> v{ver}（提交时请一并带上这些文件）");
    }

    // 指纹注入：frontend 内容一变 → rustc-env 值变化 → cargo 自动重编 crate → 宏重跑嵌入新资源
    println!("cargo:rustc-env=TAURI_FRONTEND_FP={fp}");

    // 命令名单从 src/main.rs 解析，capabilities 缺的 allow-* 也自动补上。
    // 解析为空宁可让编译失败——静默变成「没有任何命令可用」更难排查。
    let cmds = command_names();
    if cmds.is_empty() {
        panic!("未能从 src/main.rs 解析到 #[tauri::command]，请检查 build.rs 的解析逻辑");
    }
    let added = sync_capabilities(&cmds);
    if added > 0 {
        println!("cargo:warning=已自动补齐 {added} 条命令权限到 {CAPABILITIES}（提交时请一并带上）");
    }

    // AppManifest::commands 要求 'static 生命周期，build script 是短命进程，
    // 直接泄漏即可（不值得为它引入 lazy_static）
    let cmd_refs: Vec<&'static str> = cmds
        .into_iter()
        .map(|s| &*Box::leak(s.into_boxed_str()))
        .collect();
    let cmd_refs: &'static [&'static str] = Box::leak(cmd_refs.into_boxed_slice());
    let attrs = tauri_build::Attributes::default().app_manifest(
        tauri_build::AppManifest::new().commands(cmd_refs),
    );
    tauri_build::try_build(attrs).expect("tauri-build failed");
}
